spring.application.name=sgm
spring.datasource.url=jdbc:postgresql://localhost:5432/sgm_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=chave-secreta-super-longa-e-dificil-de-adivinhar-para-o-projeto-sgm-2026
jwt.expiration=86400000